// Generated by go generate; DO NOT EDIT.

package main

var KnownErrors = map[string]error {
	"ErrGoInvalidTag": ErrGoInvalidTag,
	"ErrGoMissingSymbols": ErrGoMissingSymbols,
	"ErrGoMissingTag": ErrGoMissingTag,
	"ErrMultipleLibcrypto": ErrMultipleLibcrypto,
	"ErrNoCgoInit": ErrNoCgoInit,
	"ErrNoLibcrypto": ErrNoLibcrypto,
	"ErrNoLibcryptoSO": ErrNoLibcryptoSO,
	"ErrNotCgoEnabled": ErrNotCgoEnabled,
	"ErrNotDynLinked": ErrNotDynLinked,
}
